name: Deploy to Sakura Server via FTP

on:
  push:
    branches:
      - main  # 'main' ブランチに push された際に実行される

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. FTP サーバーにデプロイ
      - name: Deploy to Sakura Server via FTP
        uses: samkirkland/ftp-deploy-action@v3
        with:
          server: ${{ secrets.FTP_SERVER }}         # FTPサーバー名（GitHub Secretsから取得）
          username: ${{ secrets.FTP_USERNAME }}     # FTPユーザー名（GitHub Secretsから取得）
          password: ${{ secrets.FTP_PASSWORD }}     # FTPパスワード（GitHub Secretsから取得）
          local-dir: ./                             # ローカルディレクトリ（GitHub Actions内のコード）
          remote-dir: /www/list-app                # さくらサーバー上のデプロイ先ディレクトリ
